language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=mocktest

after_success:
  - pip install --quiet coveralls
  - coveralls
